### ISSUE TITLE
Flwo direction and events

### ISSUE THREAD

**Issue by zebby-nick** [densen2014/BootstrapBlazor.MindMap#1]
Is it possible to add a horiztonal view? I want the tree view to essentially flow down rather than to the right? 

The javascript emits a bunch of functions like node_click. Can these be hooked up properly to C# functions?

**Comment by densen2014** [comment]
watch the oringenl codes, may be can find your answer

**Comment by zebby-nick** [comment]
https://wanglin2.github.io/mind-map/#/doc/zh/course11
Ok, Found that mindMap.setLayout('organizationStructure') will do what I need. 
Is this function exposed in the Blazor copy of the code?

**Comment by densen2014** [comment]
we will so happy if you can push your test code for help this projet better ：）

**Comment by densen2014** [comment]
I checked the code and found that this method is not copy to blqzor. I will do it it if I have time next week

**Comment by densen2014** [comment]
v8.0.2 add something

1. SetTheme, EnumMindMapTheme
2. SetLayout, EnumMindMapLayout
3. MindMapOption

https://blazor.app1.es/MindMaps


![image](https://github.com/densen2014/BootstrapBlazor.MindMap/assets/8428709/cefe32f3-b43a-4337-9798-2847a6e1064a)

**Comment by densen2014** [comment]
v8.0.4 auto reload options
